    - Pandas library is used for working and manipulating tabular data

In [2]:
## installing the pandas library
# !pip install pandas

In [108]:
# !pip install openpyxl

In [6]:
import pandas as pd
import numpy as np

- Two important data structure in Pandas
    - Pandas Series ( 1D )
    - Pandas Dataframe ( 2D - Table  Format)

## Pandas series
    -  index and data

In [11]:
x = np.array([20, 30, 40, 50])
x

array([20, 30, 40, 50])

In [22]:
# while creating a pandas series, we can provide index and data
# my_series = pd.Series(data = x, index = [100, 200, 300, 400])
# pd.Series(data = x, index = [1, 2, 3, 4])
my_series = pd.Series(data = x, index = ['a', 'b', 'c', 'd'])


print(my_series)
print(my_series.index)
print(my_series.values)

a    20
b    30
c    40
d    50
dtype: int64
Index(['a', 'b', 'c', 'd'], dtype='object')
[20 30 40 50]

In [75]:
print(dir(my_series))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__bool__', '__class__', '__column_consortium_standard__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__firstlineno__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__static_attributes__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_as_manager', '_attrs', '_binop', '_can_hold_na', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_expanddim', '_constructor_expanddim_from_mgr', '_constructor_from_mgr', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_drop_axis', '_drop_labels_or_levels', '_duplicated', '_find_valid_index', '_flags', '_flex_method', '_from_mgr', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cacher', '_get_cleaned_column_resolvers', '_get_index_resolvers', '_get_label_or_level_values', '_get_numeric_data', '_get_rows_with_mask', '_get_value', '_get_values_tuple', '_get_with', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_init_dict', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_cached', '_is_copy', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_item_cache', '_ixs', '_logical_func', '_logical_method', '_map_values', '_maybe_update_cacher', '_memory_usage', '_metadata', '_mgr', '_min_count_stat_function', '_name', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_references', '_reindex_axes', '_reindex_indexer', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_single', '_repr_data_resource_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_set_as_cached', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_labels', '_set_name', '_set_value', '_set_values', '_set_with', '_set_with_engine', '_shift_with_freq', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'backfill', 'between', 'between_time', 'bfill', 'bool', 'case_when', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'interpolate', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'list', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'memory_usage', 'min', 'mod', 'mode', 'mul', 'multiply', 'name', 'nbytes', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'radd', 'rank', 'ravel', 'rdiv', 'rdivmod', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'repeat', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'searchsorted', 'sem', 'set_axis', 'set_flags', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'std', 'str', 'struct', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_frame', 'to_hdf', 'to_json', 'to_latex', 'to_list', 'to_markdown', 'to_numpy', 'to_period', 'to_pickle', 'to_sql', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unique', 'unstack', 'update', 'value_counts', 'values', 'var', 'view', 'where', 'xs']

## Different ways to create a pandas series

In [27]:
my_series = pd.Series(data = ["rohan", "mohan", "shyam", "ghanshyam"], 
                     index = [12, 13, 14, 15])
my_series

12        rohan
13        mohan
14        shyam
15    ghanshyam
dtype: object

In [30]:
my_series = pd.Series( { "1" : "rohan", "2": "mohan", "3":"shyam" })
my_series

1    rohan
2    mohan
3    shyam
dtype: object

In [31]:
my_series = pd.Series([44, 45, 46])
my_series.to_dict()

{0: 44, 1: 45, 2: 46}

In [33]:
my_series = pd.Series(data = ["rohan", "mohan", "shyam", "ghanshyam"], 
                     index = [12, 13, 14, 15])
my_series.to_csv("test.csv")

## Accessing the values - Working with index on pandas series

In [34]:
my_series = pd.Series(data = ["rohan", "mohan", "shyam", "ghanshyam"], 
                     index = [12, 13, 14, 15])

In [43]:
# access a single element from the series
my_series[14]

'shyam'

In [47]:
my_series

12        rohan
13        mohan
14        shyam
15    ghanshyam
dtype: object

In [51]:
## loc and iloc
# my_series[12]
my_series.loc[13] ## allowing us to access the values using explicit index

'rohan'

In [57]:
# iloc allows us to access the values using implicit index (positional index)
my_series.iloc[3]

'ghanshyam'

In [59]:
my_series.loc[13:] # slicing

13        mohan
14        shyam
15    ghanshyam
dtype: object

In [60]:
my_series.iloc[1:]

13        mohan
14        shyam
15    ghanshyam
dtype: object

In [ ]:
## all mathematical functions

In [68]:
num_series = pd.Series(np.round(np.random.random(10)*100))

In [69]:
num_series

0    60.0
1    88.0
2    84.0
3    56.0
4    37.0
5    63.0
6    32.0
7    40.0
8    69.0
9    65.0
dtype: float64

In [71]:
np.sum(num_series)

np.float64(594.0)

In [72]:
num_series.sum()

np.float64(594.0)

In [73]:
num_series.sum()

np.float64(3.32365491634176e+17)

In [74]:
num_series.cumsum()

0     60.0
1    148.0
2    232.0
3    288.0
4    325.0
5    388.0
6    420.0
7    460.0
8    529.0
9    594.0
dtype: float64

In [77]:
series1 = pd.Series([1, 2, 3])
series2 = pd.Series([5, 6, 7])
series1 + series2

0     6
1     8
2    10
dtype: int64

In [78]:
series1.min(), series2.max()

(np.int64(1), np.int64(7))

In [81]:
series1.min()

np.int64(1)

# Pandas Dataframe

## creating a pandas dataframe
    - IMP: reading a csv, excel file
    - using a python dictionary
    - using a numpy matrix
    - use numpy arrays and pd series to create dataframe
    - using sql
    - using html
    - using pdf

In [82]:
my_series = pd.Series(data = ["rohan", "mohan", "shyam", "ghanshyam"], 
                     index = [12, 13, 14, 15])

my_series.values

array(['rohan', 'mohan', 'shyam', 'ghanshyam'], dtype=object)

In [93]:
## create a dataframe

my_table = pd.DataFrame( {
    "name" : ['rohan', 'mohan', 'shyam', 'ghanshyam', "sohan"], 
    "city" : ['delhi', 'mumbai', 'delhi', 'hyderabad', "mumbai"], 
    "salary": [10000, 12000, 15000, 9000 , 18000], 
    "deptt": ["finance", "marketing", "engineering", "HR", "admin"]
    
}   )

my_table

        name       city  salary        deptt
0      rohan      delhi   10000      finance
1      mohan     mumbai   12000    marketing
2      shyam      delhi   15000  engineering
3  ghanshyam  hyderabad    9000           HR
4      sohan     mumbai   18000        admin

In [94]:
my_table.shape

(5, 4)

In [95]:
my_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   city    5 non-null      object
 2   salary  5 non-null      int64
 3   deptt   5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [97]:
# giving some statistical summary of my data
my_table.describe()

             salary
count      5.000000
mean   12800.000000
std     3701.351105
min     9000.000000
25%    10000.000000
50%    12000.000000
75%    15000.000000
max    18000.000000

In [100]:
my_table.T

              0          1            2          3       4
name      rohan      mohan        shyam  ghanshyam   sohan
city      delhi     mumbai        delhi  hyderabad  mumbai
salary    10000      12000        15000       9000   18000
deptt   finance  marketing  engineering         HR   admin

In [98]:
my_table.to_dict()

{'name': {0: 'rohan', 1: 'mohan', 2: 'shyam', 3: 'ghanshyam', 4: 'sohan'},
 'city': {0: 'delhi', 1: 'mumbai', 2: 'delhi', 3: 'hyderabad', 4: 'mumbai'},
 'salary': {0: 10000, 1: 12000, 2: 15000, 3: 9000, 4: 18000},
 'deptt': {0: 'finance',
  1: 'marketing',
  2: 'engineering',
  3: 'HR',
  4: 'admin'}}

In [101]:
my_table.T.to_dict()

{0: {'name': 'rohan', 'city': 'delhi', 'salary': 10000, 'deptt': 'finance'},
 1: {'name': 'mohan', 'city': 'mumbai', 'salary': 12000, 'deptt': 'marketing'},
 2: {'name': 'shyam',
  'city': 'delhi',
  'salary': 15000,
  'deptt': 'engineering'},
 3: {'name': 'ghanshyam', 'city': 'hyderabad', 'salary': 9000, 'deptt': 'HR'},
 4: {'name': 'sohan', 'city': 'mumbai', 'salary': 18000, 'deptt': 'admin'}}

In [102]:
my_table.to_json()

'{"name":{"0":"rohan","1":"mohan","2":"shyam","3":"ghanshyam","4":"sohan"},"city":{"0":"delhi","1":"mumbai","2":"delhi","3":"hyderabad","4":"mumbai"},"salary":{"0":10000,"1":12000,"2":15000,"3":9000,"4":18000},"deptt":{"0":"finance","1":"marketing","2":"engineering","3":"HR","4":"admin"}}'

## saving the data into different formats

In [104]:
my_table.to_csv("my_table.csv", index = False)

In [109]:
my_table.to_excel("my_table.xlsx")

In [112]:
my_table["emp_id"] =  my_table.index

In [124]:
## exploring the shape and size of the dataframe

my_table

        name       city  salary        deptt  emp_id
0      rohan      delhi   10000      finance       0
1      mohan     mumbai   12000    marketing       1
2      shyam      delhi   15000  engineering       2
3  ghanshyam  hyderabad    9000           HR       3
4      sohan     mumbai   18000        admin       4

In [125]:
my_table.shape

(5, 5)

In [127]:
my_table.head(2)

    name    city  salary      deptt  emp_id
0  rohan   delhi   10000    finance       0
1  mohan  mumbai   12000  marketing       1

In [128]:
my_table.tail(2)

        name       city  salary  deptt  emp_id
3  ghanshyam  hyderabad    9000     HR       3
4      sohan     mumbai   18000  admin       4

In [145]:
my_table.sample(2)

        name       city  salary      deptt  emp_id
1      mohan     mumbai   12000  marketing       1
3  ghanshyam  hyderabad    9000         HR       3

In [153]:
my_table.index

RangeIndex(start=0, stop=5, step=1)

In [152]:
my_table.columns

Index(['name', 'city', 'salary', 'deptt', 'emp_id'], dtype='object')

In [149]:
my_table.values

array([['rohan', 'delhi', 10000, 'finance', 0],
       ['mohan', 'mumbai', 12000, 'marketing', 1],
       ['shyam', 'delhi', 15000, 'engineering', 2],
       ['ghanshyam', 'hyderabad', 9000, 'HR', 3],
       ['sohan', 'mumbai', 18000, 'admin', 4]], dtype=object)

In [154]:
my_table.dtypes

name      object
city      object
salary     int64
deptt     object
emp_id     int64
dtype: object

In [160]:
print(dir(my_table["city"]))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__bool__', '__class__', '__column_consortium_standard__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__firstlineno__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__static_attributes__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_as_manager', '_attrs', '_binop', '_cacher', '_can_hold_na', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_expanddim', '_constructor_expanddim_from_mgr', '_constructor_from_mgr', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_drop_axis', '_drop_labels_or_levels', '_duplicated', '_find_valid_index', '_flags', '_flex_method', '_from_mgr', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cacher', '_get_cleaned_column_resolvers', '_get_index_resolvers', '_get_label_or_level_values', '_get_numeric_data', '_get_rows_with_mask', '_get_value', '_get_values_tuple', '_get_with', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_init_dict', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_cached', '_is_copy', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_item_cache', '_ixs', '_logical_func', '_logical_method', '_map_values', '_maybe_update_cacher', '_memory_usage', '_metadata', '_mgr', '_min_count_stat_function', '_name', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_references', '_reindex_axes', '_reindex_indexer', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_single', '_repr_data_resource_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_set_as_cached', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_labels', '_set_name', '_set_value', '_set_values', '_set_with', '_set_with_engine', '_shift_with_freq', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'backfill', 'between', 'between_time', 'bfill', 'bool', 'case_when', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'interpolate', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'list', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'memory_usage', 'min', 'mod', 'mode', 'mul', 'multiply', 'name', 'nbytes', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'radd', 'rank', 'ravel', 'rdiv', 'rdivmod', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'repeat', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'searchsorted', 'sem', 'set_axis', 'set_flags', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'std', 'str', 'struct', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_frame', 'to_hdf', 'to_json', 'to_latex', 'to_list', 'to_markdown', 'to_numpy', 'to_period', 'to_pickle', 'to_sql', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unique', 'unstack', 'update', 'value_counts', 'values', 'var', 'view', 'where', 'xs']

In [158]:
my_table["city"].unique()

array(['delhi', 'mumbai', 'hyderabad'], dtype=object)

In [161]:
my_table["city"].nunique() ## select count(distinct city) from my_table

3

In [162]:
my_table["city"].value_counts()  # select city, count(*) from my_table group by city

city
delhi        2
mumbai       2
hyderabad    1
Name: count, dtype: int64

In [166]:
my_table["city"].value_counts(normalize=True) *100

city
delhi        40.0
mumbai       40.0
hyderabad    20.0
Name: proportion, dtype: float64

## Accessing the values in a dataframe

In [114]:
my_table

        name       city  salary        deptt  emp_id
0      rohan      delhi   10000      finance       0
1      mohan     mumbai   12000    marketing       1
2      shyam      delhi   15000  engineering       2
3  ghanshyam  hyderabad    9000           HR       3
4      sohan     mumbai   18000        admin       4

### selecting columns

In [123]:
# want to access the name column

my_table["name"] #---> pandas series (1D)

0        rohan
1        mohan
2        shyam
3    ghanshyam
4        sohan
Name: name, dtype: object

In [122]:
my_table[["name"]]

        name
0      rohan
1      mohan
2      shyam
3  ghanshyam
4      sohan

In [120]:
# want to access 2 or more columns

# columns = ["name", "salary"]

# my_table[columns]

my_table[["name", "salary"]]  # return a dataframe

        name  salary
0      rohan   10000
1      mohan   12000
2      shyam   15000
3  ghanshyam    9000
4      sohan   18000

In [121]:
my_table[["salary", "deptt"]]

   salary        deptt
0   10000      finance
1   12000    marketing
2   15000  engineering
3    9000           HR
4   18000        admin

In [169]:
my_table

        name       city  salary        deptt  emp_id
0      rohan      delhi   10000      finance       0
1      mohan     mumbai   12000    marketing       1
2      shyam      delhi   15000  engineering       2
3  ghanshyam  hyderabad    9000           HR       3
4      sohan     mumbai   18000        admin       4

### using loc and iloc

In [168]:
## loc and iloc  ( loc is for explicit index and iloc is for implicit index )

my_table.loc[0] # this will return the 0th row

name        rohan
city        delhi
salary      10000
deptt     finance
emp_id          0
Name: 0, dtype: object

In [172]:
my_table.loc[0, "name" : "deptt"]

name        rohan
city        delhi
salary      10000
deptt     finance
Name: 0, dtype: object

In [175]:
my_table

        name       city  salary        deptt  emp_id
0      rohan      delhi   10000      finance       0
1      mohan     mumbai   12000    marketing       1
2      shyam      delhi   15000  engineering       2
3  ghanshyam  hyderabad    9000           HR       3
4      sohan     mumbai   18000        admin       4

In [ ]:
my_table.loc[0, "name"]

In [174]:
my_table.iloc[0, 0] # positional index so 0th column is understood to be name

'rohan'

In [176]:
### slicing on the dataframe

In [180]:
# when using loc the end index is not excluded
my_table.loc[1:2, "name": "deptt"]

    name    city  salary        deptt
1  mohan  mumbai   12000    marketing
2  shyam   delhi   15000  engineering

In [184]:
# since we are using positional index thats why the end index is excluded
my_table.iloc[1:3, :4]

    name    city  salary        deptt
1  mohan  mumbai   12000    marketing
2  shyam   delhi   15000  engineering

In [188]:
my_table[["name", "city", "salary", "deptt"]].loc[2:3]

        name       city  salary        deptt
2      shyam      delhi   15000  engineering
3  ghanshyam  hyderabad    9000           HR

## Filter the data using boolean mask

In [196]:
my_table

        name       city  salary        deptt  emp_id
0      rohan      delhi   10000      finance       0
1      mohan     mumbai   12000    marketing       1
2      shyam      delhi   15000  engineering       2
3  ghanshyam  hyderabad    9000           HR       3
4      sohan     mumbai   18000        admin       4

In [194]:
### filter out those people whose salary is less than 15000

mask = my_table["salary"] < 15000  # --> this is returning a mask

In [195]:
my_table[mask]

        name       city  salary      deptt  emp_id
0      rohan      delhi   10000    finance       0
1      mohan     mumbai   12000  marketing       1
3  ghanshyam  hyderabad    9000         HR       3

In [199]:
## which are the people who are from the city of delhi


my_table[my_table["city"] == "delhi"]

    name   city  salary        deptt  emp_id
0  rohan  delhi   10000      finance       0
2  shyam  delhi   15000  engineering       2

In [200]:
my_table

        name       city  salary        deptt  emp_id
0      rohan      delhi   10000      finance       0
1      mohan     mumbai   12000    marketing       1
2      shyam      delhi   15000  engineering       2
3  ghanshyam  hyderabad    9000           HR       3
4      sohan     mumbai   18000        admin       4

In [210]:
## who are the top 2 people in salary

### Method 1: Sort the data and then take the top rows ( if there is a tie then it will give wrong result)

my_table.sort_values(by = "salary", ascending= False).head(2)  # top two rows


# list(my_table.sort_values(by = "salary", ascending = False)["name"][:2].values)

my_table.sort_values(by = "salary", ascending = False)["name"][:2].to_list()


### Method 2: Find out the top two salaries first and then filter based on that




### Method 3: Rank the salaries and then take rank 1 and 2

['sohan', 'shyam']

## Modify the data in dataframes