    - Pandas library is used for working and manipulating tabular data

In [2]:
## installing the pandas library
# !pip install pandas

In [108]:
# !pip install openpyxl

In [6]:
import pandas as pd
import numpy as np

- Two important data structure in Pandas
    - Pandas Series ( 1D )
    - Pandas Dataframe ( 2D - Table  Format)

## Pandas series
    -  index and data

In [11]:
x = np.array([20, 30, 40, 50])
x

array([20, 30, 40, 50])

In [22]:
# while creating a pandas series, we can provide index and data
# my_series = pd.Series(data = x, index = [100, 200, 300, 400])
# pd.Series(data = x, index = [1, 2, 3, 4])
my_series = pd.Series(data = x, index = ['a', 'b', 'c', 'd'])


print(my_series)
print(my_series.index)
print(my_series.values)

a    20
b    30
c    40
d    50
dtype: int64
Index(['a', 'b', 'c', 'd'], dtype='object')
[20 30 40 50]

In [75]:
print(dir(my_series))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__bool__', '__class__', '__column_consortium_standard__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__firstlineno__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__static_attributes__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_as_manager', '_attrs', '_binop', '_can_hold_na', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_expanddim', '_constructor_expanddim_from_mgr', '_constructor_from_mgr', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_drop_axis', '_drop_labels_or_levels', '_duplicated', '_find_valid_index', '_flags', '_flex_method', '_from_mgr', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cacher', '_get_cleaned_column_resolvers', '_get_index_resolvers', '_get_label_or_level_values', '_get_numeric_data', '_get_rows_with_mask', '_get_value', '_get_values_tuple', '_get_with', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_init_dict', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_cached', '_is_copy', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_item_cache', '_ixs', '_logical_func', '_logical_method', '_map_values', '_maybe_update_cacher', '_memory_usage', '_metadata', '_mgr', '_min_count_stat_function', '_name', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_references', '_reindex_axes', '_reindex_indexer', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_single', '_repr_data_resource_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_set_as_cached', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_labels', '_set_name', '_set_value', '_set_values', '_set_with', '_set_with_engine', '_shift_with_freq', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'backfill', 'between', 'between_time', 'bfill', 'bool', 'case_when', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'interpolate', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'list', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'memory_usage', 'min', 'mod', 'mode', 'mul', 'multiply', 'name', 'nbytes', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'radd', 'rank', 'ravel', 'rdiv', 'rdivmod', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'repeat', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'searchsorted', 'sem', 'set_axis', 'set_flags', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'std', 'str', 'struct', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_frame', 'to_hdf', 'to_json', 'to_latex', 'to_list', 'to_markdown', 'to_numpy', 'to_period', 'to_pickle', 'to_sql', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unique', 'unstack', 'update', 'value_counts', 'values', 'var', 'view', 'where', 'xs']

## Different ways to create a pandas series

In [27]:
my_series = pd.Series(data = ["rohan", "mohan", "shyam", "ghanshyam"], 
                     index = [12, 13, 14, 15])
my_series

12        rohan
13        mohan
14        shyam
15    ghanshyam
dtype: object

In [30]:
my_series = pd.Series( { "1" : "rohan", "2": "mohan", "3":"shyam" })
my_series

1    rohan
2    mohan
3    shyam
dtype: object

In [31]:
my_series = pd.Series([44, 45, 46])
my_series.to_dict()

{0: 44, 1: 45, 2: 46}

In [33]:
my_series = pd.Series(data = ["rohan", "mohan", "shyam", "ghanshyam"], 
                     index = [12, 13, 14, 15])
my_series.to_csv("test.csv")

## Accessing the values - Working with index on pandas series

In [34]:
my_series = pd.Series(data = ["rohan", "mohan", "shyam", "ghanshyam"], 
                     index = [12, 13, 14, 15])

In [43]:
# access a single element from the series
my_series[14]

'shyam'

In [47]:
my_series

12        rohan
13        mohan
14        shyam
15    ghanshyam
dtype: object

In [51]:
## loc and iloc
# my_series[12]
my_series.loc[13] ## allowing us to access the values using explicit index

'rohan'

In [57]:
# iloc allows us to access the values using implicit index (positional index)
my_series.iloc[3]

'ghanshyam'

In [59]:
my_series.loc[13:] # slicing

13        mohan
14        shyam
15    ghanshyam
dtype: object

In [60]:
my_series.iloc[1:]

13        mohan
14        shyam
15    ghanshyam
dtype: object

In [ ]:
## all mathematical functions

In [68]:
num_series = pd.Series(np.round(np.random.random(10)*100))

In [69]:
num_series

0    60.0
1    88.0
2    84.0
3    56.0
4    37.0
5    63.0
6    32.0
7    40.0
8    69.0
9    65.0
dtype: float64

In [71]:
np.sum(num_series)

np.float64(594.0)

In [72]:
num_series.sum()

np.float64(594.0)

In [73]:
num_series.sum()

np.float64(3.32365491634176e+17)

In [74]:
num_series.cumsum()

0     60.0
1    148.0
2    232.0
3    288.0
4    325.0
5    388.0
6    420.0
7    460.0
8    529.0
9    594.0
dtype: float64

In [77]:
series1 = pd.Series([1, 2, 3])
series2 = pd.Series([5, 6, 7])
series1 + series2

0     6
1     8
2    10
dtype: int64

In [78]:
series1.min(), series2.max()

(np.int64(1), np.int64(7))

In [81]:
series1.min()

np.int64(1)

# Pandas Dataframe

## creating a pandas dataframe
    - IMP: reading a csv, excel file
    - using a python dictionary
    - using a numpy matrix
    - use numpy arrays and pd series to create dataframe
    - using sql
    - using html
    - using pdf

In [211]:
my_series = pd.Series(data = ["rohan", "mohan", "shyam", "ghanshyam"], 
                     index = [12, 13, 14, 15])

my_series.values

array(['rohan', 'mohan', 'shyam', 'ghanshyam'], dtype=object)

In [212]:
## create a dataframe

my_table = pd.DataFrame( {
    "name" : ['rohan', 'mohan', 'shyam', 'ghanshyam', "sohan"], 
    "city" : ['delhi', 'mumbai', 'delhi', 'hyderabad', "mumbai"], 
    "salary": [10000, 12000, 15000, 9000 , 18000], 
    "deptt": ["finance", "marketing", "engineering", "HR", "admin"]
    
}   )

my_table

        name       city  salary        deptt
0      rohan      delhi   10000      finance
1      mohan     mumbai   12000    marketing
2      shyam      delhi   15000  engineering
3  ghanshyam  hyderabad    9000           HR
4      sohan     mumbai   18000        admin

In [219]:
## create a pandas dataframe using a numpy

df = pd.DataFrame(data  = np.random.randn(20, 4), columns=["marks", "salary", "height", "price"])
df

       marks    salary    height     price
0  -0.711900  0.895411  0.471759 -1.933023
1  -0.028705  0.462003 -0.044652  2.402441
2  -0.327953  0.635018 -0.594748 -0.641126
3  -0.473745  0.403463 -0.371221  1.400949
4  -0.928551 -0.337928  0.345180  0.381274
5   0.110115  3.407725 -0.763736 -0.164972
6  -0.704609 -1.263448  0.441399 -0.142753
7   0.594897 -0.454372 -1.068445 -0.289523
8  -0.717478  1.575488 -0.500084 -1.568811
9  -0.761934 -0.266073  2.528402 -0.838323
10 -0.027389 -0.222248 -0.068861 -0.245019
11  0.279222  0.029369 -0.420286 -0.627613
12 -0.439997 -0.223136  0.202347  0.660218
13  0.528607  0.161995  1.530792  0.485629
14  0.231636 -0.334088 -0.169489  0.294393
15  0.765103  0.699796  1.520949 -0.292334
16 -1.557716 -1.027902 -1.260216 -0.764320
17  0.679515  1.129996  1.015778  1.530482
18 -0.680768  0.639880 -0.754072  0.413202
19 -1.126937 -0.592929  0.001624 -0.483085

In [94]:
my_table.shape

(5, 4)

In [95]:
my_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   city    5 non-null      object
 2   salary  5 non-null      int64
 3   deptt   5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [97]:
# giving some statistical summary of my data
my_table.describe()

             salary
count      5.000000
mean   12800.000000
std     3701.351105
min     9000.000000
25%    10000.000000
50%    12000.000000
75%    15000.000000
max    18000.000000

In [100]:
my_table.T

              0          1            2          3       4
name      rohan      mohan        shyam  ghanshyam   sohan
city      delhi     mumbai        delhi  hyderabad  mumbai
salary    10000      12000        15000       9000   18000
deptt   finance  marketing  engineering         HR   admin

## saving the data into different formats

In [98]:
my_table.to_dict()

{'name': {0: 'rohan', 1: 'mohan', 2: 'shyam', 3: 'ghanshyam', 4: 'sohan'},
 'city': {0: 'delhi', 1: 'mumbai', 2: 'delhi', 3: 'hyderabad', 4: 'mumbai'},
 'salary': {0: 10000, 1: 12000, 2: 15000, 3: 9000, 4: 18000},
 'deptt': {0: 'finance',
  1: 'marketing',
  2: 'engineering',
  3: 'HR',
  4: 'admin'}}

In [101]:
my_table.T.to_dict()

{0: {'name': 'rohan', 'city': 'delhi', 'salary': 10000, 'deptt': 'finance'},
 1: {'name': 'mohan', 'city': 'mumbai', 'salary': 12000, 'deptt': 'marketing'},
 2: {'name': 'shyam',
  'city': 'delhi',
  'salary': 15000,
  'deptt': 'engineering'},
 3: {'name': 'ghanshyam', 'city': 'hyderabad', 'salary': 9000, 'deptt': 'HR'},
 4: {'name': 'sohan', 'city': 'mumbai', 'salary': 18000, 'deptt': 'admin'}}

In [102]:
my_table.to_json()

'{"name":{"0":"rohan","1":"mohan","2":"shyam","3":"ghanshyam","4":"sohan"},"city":{"0":"delhi","1":"mumbai","2":"delhi","3":"hyderabad","4":"mumbai"},"salary":{"0":10000,"1":12000,"2":15000,"3":9000,"4":18000},"deptt":{"0":"finance","1":"marketing","2":"engineering","3":"HR","4":"admin"}}'

In [104]:
my_table.to_csv("my_table.csv", index = False)

In [109]:
my_table.to_excel("my_table.xlsx")

In [112]:
my_table["emp_id"] =  my_table.index

In [124]:
## exploring the shape and size of the dataframe

my_table

        name       city  salary        deptt  emp_id
0      rohan      delhi   10000      finance       0
1      mohan     mumbai   12000    marketing       1
2      shyam      delhi   15000  engineering       2
3  ghanshyam  hyderabad    9000           HR       3
4      sohan     mumbai   18000        admin       4

In [125]:
my_table.shape

(5, 5)

In [127]:
my_table.head(2)

    name    city  salary      deptt  emp_id
0  rohan   delhi   10000    finance       0
1  mohan  mumbai   12000  marketing       1

In [128]:
my_table.tail(2)

        name       city  salary  deptt  emp_id
3  ghanshyam  hyderabad    9000     HR       3
4      sohan     mumbai   18000  admin       4

In [145]:
my_table.sample(2)

        name       city  salary      deptt  emp_id
1      mohan     mumbai   12000  marketing       1
3  ghanshyam  hyderabad    9000         HR       3

In [153]:
my_table.index

RangeIndex(start=0, stop=5, step=1)

In [152]:
my_table.columns

Index(['name', 'city', 'salary', 'deptt', 'emp_id'], dtype='object')

In [149]:
my_table.values

array([['rohan', 'delhi', 10000, 'finance', 0],
       ['mohan', 'mumbai', 12000, 'marketing', 1],
       ['shyam', 'delhi', 15000, 'engineering', 2],
       ['ghanshyam', 'hyderabad', 9000, 'HR', 3],
       ['sohan', 'mumbai', 18000, 'admin', 4]], dtype=object)

In [154]:
my_table.dtypes

name      object
city      object
salary     int64
deptt     object
emp_id     int64
dtype: object

In [160]:
print(dir(my_table["city"]))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__bool__', '__class__', '__column_consortium_standard__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__firstlineno__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__static_attributes__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_as_manager', '_attrs', '_binop', '_cacher', '_can_hold_na', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_expanddim', '_constructor_expanddim_from_mgr', '_constructor_from_mgr', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_drop_axis', '_drop_labels_or_levels', '_duplicated', '_find_valid_index', '_flags', '_flex_method', '_from_mgr', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cacher', '_get_cleaned_column_resolvers', '_get_index_resolvers', '_get_label_or_level_values', '_get_numeric_data', '_get_rows_with_mask', '_get_value', '_get_values_tuple', '_get_with', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_init_dict', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_cached', '_is_copy', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_item_cache', '_ixs', '_logical_func', '_logical_method', '_map_values', '_maybe_update_cacher', '_memory_usage', '_metadata', '_mgr', '_min_count_stat_function', '_name', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_references', '_reindex_axes', '_reindex_indexer', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_single', '_repr_data_resource_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_set_as_cached', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_labels', '_set_name', '_set_value', '_set_values', '_set_with', '_set_with_engine', '_shift_with_freq', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'backfill', 'between', 'between_time', 'bfill', 'bool', 'case_when', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'interpolate', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'list', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'memory_usage', 'min', 'mod', 'mode', 'mul', 'multiply', 'name', 'nbytes', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'radd', 'rank', 'ravel', 'rdiv', 'rdivmod', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'repeat', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'searchsorted', 'sem', 'set_axis', 'set_flags', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'std', 'str', 'struct', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_frame', 'to_hdf', 'to_json', 'to_latex', 'to_list', 'to_markdown', 'to_numpy', 'to_period', 'to_pickle', 'to_sql', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unique', 'unstack', 'update', 'value_counts', 'values', 'var', 'view', 'where', 'xs']

In [158]:
my_table["city"].unique()

array(['delhi', 'mumbai', 'hyderabad'], dtype=object)

In [161]:
my_table["city"].nunique() ## select count(distinct city) from my_table

3

In [162]:
my_table["city"].value_counts()  # select city, count(*) from my_table group by city

city
delhi        2
mumbai       2
hyderabad    1
Name: count, dtype: int64

In [166]:
my_table["city"].value_counts(normalize=True) *100

city
delhi        40.0
mumbai       40.0
hyderabad    20.0
Name: proportion, dtype: float64

## Accessing the values in a dataframe

In [114]:
my_table

        name       city  salary        deptt  emp_id
0      rohan      delhi   10000      finance       0
1      mohan     mumbai   12000    marketing       1
2      shyam      delhi   15000  engineering       2
3  ghanshyam  hyderabad    9000           HR       3
4      sohan     mumbai   18000        admin       4

### selecting columns

In [123]:
# want to access the name column

my_table["name"] #---> pandas series (1D)

0        rohan
1        mohan
2        shyam
3    ghanshyam
4        sohan
Name: name, dtype: object

In [122]:
my_table[["name"]]

        name
0      rohan
1      mohan
2      shyam
3  ghanshyam
4      sohan

In [120]:
# want to access 2 or more columns

# columns = ["name", "salary"]

# my_table[columns]

my_table[["name", "salary"]]  # return a dataframe

        name  salary
0      rohan   10000
1      mohan   12000
2      shyam   15000
3  ghanshyam    9000
4      sohan   18000

In [121]:
my_table[["salary", "deptt"]]

   salary        deptt
0   10000      finance
1   12000    marketing
2   15000  engineering
3    9000           HR
4   18000        admin

In [169]:
my_table

        name       city  salary        deptt  emp_id
0      rohan      delhi   10000      finance       0
1      mohan     mumbai   12000    marketing       1
2      shyam      delhi   15000  engineering       2
3  ghanshyam  hyderabad    9000           HR       3
4      sohan     mumbai   18000        admin       4

### using loc and iloc

In [168]:
## loc and iloc  ( loc is for explicit index and iloc is for implicit index )

my_table.loc[0] # this will return the 0th row

name        rohan
city        delhi
salary      10000
deptt     finance
emp_id          0
Name: 0, dtype: object

In [172]:
my_table.loc[0, "name" : "deptt"]

name        rohan
city        delhi
salary      10000
deptt     finance
Name: 0, dtype: object

In [175]:
my_table

        name       city  salary        deptt  emp_id
0      rohan      delhi   10000      finance       0
1      mohan     mumbai   12000    marketing       1
2      shyam      delhi   15000  engineering       2
3  ghanshyam  hyderabad    9000           HR       3
4      sohan     mumbai   18000        admin       4

In [ ]:
my_table.loc[0, "name"]

In [174]:
my_table.iloc[0, 0] # positional index so 0th column is understood to be name

'rohan'

In [176]:
### slicing on the dataframe

In [180]:
# when using loc the end index is not excluded
my_table.loc[1:2, "name": "deptt"]

    name    city  salary        deptt
1  mohan  mumbai   12000    marketing
2  shyam   delhi   15000  engineering

In [184]:
# since we are using positional index thats why the end index is excluded
my_table.iloc[1:3, :4]

    name    city  salary        deptt
1  mohan  mumbai   12000    marketing
2  shyam   delhi   15000  engineering

In [188]:
my_table[["name", "city", "salary", "deptt"]].loc[2:3]

        name       city  salary        deptt
2      shyam      delhi   15000  engineering
3  ghanshyam  hyderabad    9000           HR

## Filter the data using boolean mask

In [196]:
my_table

        name       city  salary        deptt  emp_id
0      rohan      delhi   10000      finance       0
1      mohan     mumbai   12000    marketing       1
2      shyam      delhi   15000  engineering       2
3  ghanshyam  hyderabad    9000           HR       3
4      sohan     mumbai   18000        admin       4

In [194]:
### filter out those people whose salary is less than 15000

mask = my_table["salary"] < 15000  # --> this is returning a mask

In [195]:
my_table[mask]

        name       city  salary      deptt  emp_id
0      rohan      delhi   10000    finance       0
1      mohan     mumbai   12000  marketing       1
3  ghanshyam  hyderabad    9000         HR       3

In [199]:
## which are the people who are from the city of delhi


my_table[my_table["city"] == "delhi"]

    name   city  salary        deptt  emp_id
0  rohan  delhi   10000      finance       0
2  shyam  delhi   15000  engineering       2

In [200]:
my_table

        name       city  salary        deptt  emp_id
0      rohan      delhi   10000      finance       0
1      mohan     mumbai   12000    marketing       1
2      shyam      delhi   15000  engineering       2
3  ghanshyam  hyderabad    9000           HR       3
4      sohan     mumbai   18000        admin       4

# sorting the data in the table

In [210]:
## who are the top 2 people in salary

### Method 1: Sort the data and then take the top rows ( if there is a tie then it will give wrong result)

my_table.sort_values(by = "salary", ascending= False).head(2)  # top two rows


# list(my_table.sort_values(by = "salary", ascending = False)["name"][:2].values)

my_table.sort_values(by = "salary", ascending = False)["name"][:2].to_list()


### Method 2: Find out the top two salaries first and then filter based on that




### Method 3: Rank the salaries and then take rank 1 and 2

['sohan', 'shyam']

## Modify the data in dataframes

In [222]:
## create a new column that has values "low salary" if salary < 10000, "medium salary" < 15000, "high salary"

my_table

        name       city  salary        deptt
0      rohan      delhi   10000      finance
1      mohan     mumbai   12000    marketing
2      shyam      delhi   15000  engineering
3  ghanshyam  hyderabad    9000           HR
4      sohan     mumbai   18000        admin

In [229]:
salary_label = []

for salary in my_table["salary"]:
    label = "low salary" if salary < 10000 else ("medium salary" if salary < 15000 else "high salary")
    salary_label.append(label)


## assign a column to the table
my_table["salary_label"] = salary_label


my_table

        name       city  salary        deptt   salary_label
0      rohan      delhi   10000      finance  medium salary
1      mohan     mumbai   12000    marketing  medium salary
2      shyam      delhi   15000  engineering    high salary
3  ghanshyam  hyderabad    9000           HR     low salary
4      sohan     mumbai   18000        admin    high salary

In [230]:
## Assignment : Use np. where to create the salary label
my_table["salary"]

0    10000
1    12000
2    15000
3     9000
4    18000
Name: salary, dtype: int64

In [234]:
salary_labels  = my_table["salary"].apply(lambda x : "low salary" if x < 10000 else ("medium salary" if x < 15000 else "high salary"))

my_table["salary_label2"] = salary_labels

In [235]:
my_table

        name       city  salary        deptt   salary_label  salary_label2
0      rohan      delhi   10000      finance  medium salary  medium salary
1      mohan     mumbai   12000    marketing  medium salary  medium salary
2      shyam      delhi   15000  engineering    high salary    high salary
3  ghanshyam  hyderabad    9000           HR     low salary     low salary
4      sohan     mumbai   18000        admin    high salary    high salary

In [241]:
## add a bonus column which is 20% for delhi, 10% for mumbai, 15% for hyderabad and then apply the bonus to the salary and show the new salary

my_table["bonus"] = my_table["city"].apply(lambda x : 0.2  if x == "delhi" else (0.1 if x == "mumbai" else 0.15))
my_table["new_salary"] = my_table["salary"] * (my_table["bonus"] + 1)
my_table

,name,city,salary,deptt,salary_label,salary_label2,bonus,new_salary
0,rohan,delhi,10000,finance,medium salary,medium salary,0.20,12000.0
1,mohan,mumbai,12000,marketing,medium salary,medium salary,0.10,13200.0
2,shyam,delhi,15000,engineering,high salary,high salary,0.20,18000.0
3,ghanshyam,hyderabad,9000,HR,low salary,low salary,0.15,10350.0
4,sohan,mumbai,18000,admin,high salary,high salary,0.10,19800.0

In [243]:
my_table

,name,city,salary,deptt,salary_label,salary_label2,bonus,new_salary
0,rohan,delhi,10000,finance,medium salary,medium salary,0.20,12000.0
1,mohan,mumbai,12000,marketing,medium salary,medium salary,0.10,13200.0
2,shyam,delhi,15000,engineering,high salary,high salary,0.20,18000.0
3,ghanshyam,hyderabad,9000,HR,low salary,low salary,0.15,10350.0
4,sohan,mumbai,18000,admin,high salary,high salary,0.10,19800.0

In [245]:
bonus_table = pd.DataFrame({ "area" : [ "delhi", "mumbai" ], 
                           "bonus_amount": [0.2, 0.1]})

bonus_table

     area  bonus
0   delhi    0.2
1  mumbai    0.1

In [247]:
my_table

,name,city,salary,deptt,salary_label,salary_label2,bonus,new_salary
0,rohan,delhi,10000,finance,medium salary,medium salary,0.20,12000.0
1,mohan,mumbai,12000,marketing,medium salary,medium salary,0.10,13200.0
2,shyam,delhi,15000,engineering,high salary,high salary,0.20,18000.0
3,ghanshyam,hyderabad,9000,HR,low salary,low salary,0.15,10350.0
4,sohan,mumbai,18000,admin,high salary,high salary,0.10,19800.0

In [255]:
my_table = pd.DataFrame( {
    "name" : ['rohan', 'mohan', 'shyam', 'ghanshyam', "sohan"], 
    "city" : ['delhi', 'mumbai', 'delhi', 'hyderabad', "mumbai"], 
    "salary": [10000, 12000, 15000, 9000 , 18000], 
    "deptt": ["finance", "marketing", "engineering", "HR", "admin"]
    
}   )


bonus_table = pd.DataFrame({ "area" : [ "delhi", "mumbai" , "kolkata"], 
                           "bonus_amount": [0.2, 0.1, 0.3]})

print(bonus_table)

print(my_table)

      area  bonus_amount
0    delhi           0.2
1   mumbai           0.1
2  kolkata           0.3
        name       city  salary        deptt
0      rohan      delhi   10000      finance
1      mohan     mumbai   12000    marketing
2      shyam      delhi   15000  engineering
3  ghanshyam  hyderabad    9000           HR
4      sohan     mumbai   18000        admin

In [256]:
my_table

        name       city  salary        deptt
0      rohan      delhi   10000      finance
1      mohan     mumbai   12000    marketing
2      shyam      delhi   15000  engineering
3  ghanshyam  hyderabad    9000           HR
4      sohan     mumbai   18000        admin

In [261]:
## only those rows which are present in both left and right will be kept
pd.merge( left = my_table, right= bonus_table, how = "inner", left_on = "city", right_on="area")

    name    city  salary        deptt    area  bonus_amount
0  rohan   delhi   10000      finance   delhi           0.2
1  mohan  mumbai   12000    marketing  mumbai           0.1
2  shyam   delhi   15000  engineering   delhi           0.2
3  sohan  mumbai   18000        admin  mumbai           0.1

In [262]:
## left join ---> it will keep all the rows from the left table 
pd.merge( left = my_table, right= bonus_table, how = "left", left_on = "city", right_on="area")

        name       city  salary        deptt    area  bonus_amount
0      rohan      delhi   10000      finance   delhi           0.2
1      mohan     mumbai   12000    marketing  mumbai           0.1
2      shyam      delhi   15000  engineering   delhi           0.2
3  ghanshyam  hyderabad    9000           HR     NaN           NaN
4      sohan     mumbai   18000        admin  mumbai           0.1

In [263]:
## right join ---> it will keep all the rows from the right table 
pd.merge( left = my_table, right= bonus_table, how = "right", left_on = "city", right_on="area")

    name    city   salary        deptt     area  bonus_amount
0  rohan   delhi  10000.0      finance    delhi           0.2
1  shyam   delhi  15000.0  engineering    delhi           0.2
2  mohan  mumbai  12000.0    marketing   mumbai           0.1
3  sohan  mumbai  18000.0        admin   mumbai           0.1
4    NaN     NaN      NaN          NaN  kolkata           0.3

In [260]:
## outer join ---> it will keep all the rows from both the sides 
pd.merge( left = my_table, right= bonus_table, how = "outer", left_on = "city", right_on="area")

        name       city   salary        deptt     area  bonus_amount
0      rohan      delhi  10000.0      finance    delhi           0.2
1      shyam      delhi  15000.0  engineering    delhi           0.2
2  ghanshyam  hyderabad   9000.0           HR      NaN           NaN
3        NaN        NaN      NaN          NaN  kolkata           0.3
4      mohan     mumbai  12000.0    marketing   mumbai           0.1
5      sohan     mumbai  18000.0        admin   mumbai           0.1

In [276]:
merged  = pd.merge( left = my_table, right= bonus_table, how = "left", left_on = "city", right_on="area")

In [277]:
merged

        name       city  salary        deptt    area  bonus_amount
0      rohan      delhi   10000      finance   delhi           0.2
1      mohan     mumbai   12000    marketing  mumbai           0.1
2      shyam      delhi   15000  engineering   delhi           0.2
3  ghanshyam  hyderabad    9000           HR     NaN           NaN
4      sohan     mumbai   18000        admin  mumbai           0.1

In [274]:
## handle the missing value here by imputing a default bonus of 5%

merged["bonus_amount"] = merged["bonus_amount"].apply( lambda x: x if pd.notnull(x) else 0.05 )

In [275]:
merged

        name       city  salary        deptt    area  bonus_amount
0      rohan      delhi   10000      finance   delhi          0.20
1      mohan     mumbai   12000    marketing  mumbai          0.10
2      shyam      delhi   15000  engineering   delhi          0.20
3  ghanshyam  hyderabad    9000           HR     NaN          0.05
4      sohan     mumbai   18000        admin  mumbai          0.10

In [281]:
merged["bonus_amount"]

0    0.2
1    0.1
2    0.2
3    NaN
4    0.1
Name: bonus_amount, dtype: float64

In [284]:
merged["updated_bonus"] =   np.where(pd.notnull(merged["bonus_amount"]), merged["bonus_amount"], 0.05 ) # much faster than using apply

In [285]:
merged

,name,city,salary,deptt,area,bonus_amount,updated_bonus
0,rohan,delhi,10000,finance,delhi,0.2,0.20
1,mohan,mumbai,12000,marketing,mumbai,0.1,0.10
2,shyam,delhi,15000,engineering,delhi,0.2,0.20
3,ghanshyam,hyderabad,9000,HR,NaN,NaN,0.05
4,sohan,mumbai,18000,admin,mumbai,0.1,0.10

In [287]:
merged["updated_bonus2"]  =  merged["bonus_amount"].fillna(0.02)
merged

,name,city,salary,deptt,area,bonus_amount,updated_bonus,updated_bonus2
0,rohan,delhi,10000,finance,delhi,0.2,0.20,0.20
1,mohan,mumbai,12000,marketing,mumbai,0.1,0.10,0.10
2,shyam,delhi,15000,engineering,delhi,0.2,0.20,0.20
3,ghanshyam,hyderabad,9000,HR,NaN,NaN,0.05,0.02
4,sohan,mumbai,18000,admin,mumbai,0.1,0.10,0.10

In [290]:
merged["new_salary"] =  merged["salary"] * (1+merged["updated_bonus2"])
merged

,name,city,salary,deptt,area,bonus_amount,updated_bonus,updated_bonus2,new_salary
0,rohan,delhi,10000,finance,delhi,0.2,0.20,0.20,12000.0
1,mohan,mumbai,12000,marketing,mumbai,0.1,0.10,0.10,13200.0
2,shyam,delhi,15000,engineering,delhi,0.2,0.20,0.20,18000.0
3,ghanshyam,hyderabad,9000,HR,NaN,NaN,0.05,0.02,9180.0
4,sohan,mumbai,18000,admin,mumbai,0.1,0.10,0.10,19800.0

In [301]:
## till now we have used apply on a single column. We can also use apply on multiple columns

merged[["salary", "updated_bonus2"]].apply(lambda x : x[0] * (1+x[1]) ,axis = 1)

/var/folders/st/b0hjmx2s42dbbvjsct0_5c300000gn/T/ipykernel_84217/1030876930.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  merged[["salary", "updated_bonus2"]].apply(lambda x : x [0] * (1+x[1]) ,axis = 1)

0    12000.0
1    13200.0
2    18000.0
3     9180.0
4    19800.0
dtype: float64

In [305]:
merged["appraised_salary"] =   merged.apply(lambda x : x["salary"] * (1+x["updated_bonus2"]) ,axis = 1)
merged

,name,city,salary,deptt,area,bonus_amount,updated_bonus,updated_bonus2,new_salary,appraised_salary
0,rohan,delhi,10000,finance,delhi,0.2,0.20,0.20,12000.0,12000.0
1,mohan,mumbai,12000,marketing,mumbai,0.1,0.10,0.10,13200.0,13200.0
2,shyam,delhi,15000,engineering,delhi,0.2,0.20,0.20,18000.0,18000.0
3,ghanshyam,hyderabad,9000,HR,NaN,NaN,0.05,0.02,9180.0,9180.0
4,sohan,mumbai,18000,admin,mumbai,0.1,0.10,0.10,19800.0,19800.0

In [272]:
pd.notnull(x)

array([ True,  True,  True,  True])

In [271]:
pd.isnull(1)

False

## adding some rows to the table

In [318]:
emp_table = pd.concat([my_table, pd.DataFrame({ "name": ["Mahesh", "Ramesh"], 
                                 "city":["kolkata", "kolkata"], 
                                 "salary":[4000, 8000], 
                                 "deptt":["HR", "engineering"]
                                 })],ignore_index = True )

emp_table

        name       city  salary        deptt
0      rohan      delhi   10000      finance
1      mohan     mumbai   12000    marketing
2      shyam      delhi   15000  engineering
3  ghanshyam  hyderabad    9000           HR
4      sohan     mumbai   18000        admin
5     Mahesh    kolkata    4000           HR
6     Ramesh    kolkata    8000  engineering

## groupby and aggregation

In [319]:
emp_table

        name       city  salary        deptt
0      rohan      delhi   10000      finance
1      mohan     mumbai   12000    marketing
2      shyam      delhi   15000  engineering
3  ghanshyam  hyderabad    9000           HR
4      sohan     mumbai   18000        admin
5     Mahesh    kolkata    4000           HR
6     Ramesh    kolkata    8000  engineering

In [325]:
## how many employees are there in each city. 

emp_table.groupby(["city"])[["name"]].count()

           name
city
delhi         2
hyderabad     1
kolkata       2
mumbai        2

In [329]:
## how many employees working in each department
emp_table.groupby("deptt")[["name"]].count()

             name
deptt
HR              2
admin           1
engineering     2
finance         1
marketing       1

        name       city  salary        deptt
0      rohan      delhi   10000      finance
1      mohan     mumbai   12000    marketing
2      shyam      delhi   15000  engineering
3  ghanshyam  hyderabad    9000           HR
4      sohan     mumbai   18000        admin
5     Mahesh    kolkata    4000           HR
6     Ramesh    kolkata    8000  engineering

In [330]:
## average salary city wise
emp_table.groupby("city")["salary"].mean()

city
delhi        12500.0
hyderabad     9000.0
kolkata       6000.0
mumbai       15000.0
Name: salary, dtype: float64

In [337]:
# filter the data for delhi and find the average
emp_table[emp_table["city"] == "mumbai"]["salary"].mean()

np.float64(15000.0)

In [348]:
## what is the min and max salary in each city

pd.concat([emp_table.groupby("city")["salary"].max(), 
           emp_table.groupby("city")["salary"].min()], axis = 1).reset_index()

        city  salary  salary
0      delhi   15000   10000
1  hyderabad    9000    9000
2    kolkata    8000    4000
3     mumbai   18000   12000

In [355]:
emp_table.groupby("city")["salary"].agg(["min", "max", "mean"]).reset_index()

        city    min    max     mean
0      delhi  10000  15000  12500.0
1  hyderabad   9000   9000   9000.0
2    kolkata   4000   8000   6000.0
3     mumbai  12000  18000  15000.0

In [356]:
emp_table

        name       city  salary        deptt
0      rohan      delhi   10000      finance
1      mohan     mumbai   12000    marketing
2      shyam      delhi   15000  engineering
3  ghanshyam  hyderabad    9000           HR
4      sohan     mumbai   18000        admin
5     Mahesh    kolkata    4000           HR
6     Ramesh    kolkata    8000  engineering

In [364]:
## How many employes earn more than average salary


# this will filter the data for those who earn more than the average
emp_table[emp_table["salary"] > np.mean(emp_table["salary"])]

more_than_average = (emp_table[emp_table["salary"] > emp_table["salary"].mean()])


## i want to create flag that is True if person earns more than the average else False
emp_table["salary_more_than_average"] =   emp_table["salary"].apply(lambda x : True if x > np.mean(emp_table["salary"]) else False)
emp_table

        name       city  salary        deptt  salary_more_than_average
0      rohan      delhi   10000      finance                     False
1      mohan     mumbai   12000    marketing                      True
2      shyam      delhi   15000  engineering                      True
3  ghanshyam  hyderabad    9000           HR                     False
4      sohan     mumbai   18000        admin                      True
5     Mahesh    kolkata    4000           HR                     False
6     Ramesh    kolkata    8000  engineering                     False

In [365]:
## Add a new column that shows the average salary of that city

emp_table

        name       city  salary        deptt  salary_more_than_average
0      rohan      delhi   10000      finance                     False
1      mohan     mumbai   12000    marketing                      True
2      shyam      delhi   15000  engineering                      True
3  ghanshyam  hyderabad    9000           HR                     False
4      sohan     mumbai   18000        admin                      True
5     Mahesh    kolkata    4000           HR                     False
6     Ramesh    kolkata    8000  engineering                     False

In [374]:
city_average = emp_table.groupby("city")[["salary"]].mean().reset_index()
city_average = city_average.rename({"salary":"avg_city_salary"}, axis = 1)
city_average

        city  avg_city_salary
0      delhi          12500.0
1  hyderabad           9000.0
2    kolkata           6000.0
3     mumbai          15000.0

In [382]:
pd.merge(emp_table, city_average, left_on= "city", right_on="city", how = "left")

,name,city,salary,deptt,salary_more_than_average,avg_city_salary
0,rohan,delhi,10000,finance,False,12500.0
1,mohan,mumbai,12000,marketing,True,15000.0
2,shyam,delhi,15000,engineering,True,12500.0
3,ghanshyam,hyderabad,9000,HR,False,9000.0
4,sohan,mumbai,18000,admin,True,15000.0
5,Mahesh,kolkata,4000,HR,False,6000.0
6,Ramesh,kolkata,8000,engineering,False,6000.0

In [385]:
merged = emp_table.join(city_average, how = "left",  lsuffix="x", rsuffix="y")
merged

,name,cityx,salary,deptt,salary_more_than_average,cityy,avg_city_salary
0,rohan,delhi,10000,finance,False,delhi,12500.0
1,mohan,mumbai,12000,marketing,True,hyderabad,9000.0
2,shyam,delhi,15000,engineering,True,kolkata,6000.0
3,ghanshyam,hyderabad,9000,HR,False,mumbai,15000.0
4,sohan,mumbai,18000,admin,True,NaN,NaN
5,Mahesh,kolkata,4000,HR,False,NaN,NaN
6,Ramesh,kolkata,8000,engineering,False,NaN,NaN

In [387]:
## how many employees are earning more than the average salary of their city ( groupby and join or groupby transform )


merged["earns_more_than_city_avg"] =   merged["salary"] > merged["avg_city_salary"]
merged

,name,cityx,salary,deptt,salary_more_than_average,cityy,avg_city_salary,earns_more_than_city_avg
0,rohan,delhi,10000,finance,False,delhi,12500.0,False
1,mohan,mumbai,12000,marketing,True,hyderabad,9000.0,True
2,shyam,delhi,15000,engineering,True,kolkata,6000.0,True
3,ghanshyam,hyderabad,9000,HR,False,mumbai,15000.0,False
4,sohan,mumbai,18000,admin,True,NaN,NaN,False
5,Mahesh,kolkata,4000,HR,False,NaN,NaN,False
6,Ramesh,kolkata,8000,engineering,False,NaN,NaN,False

## drop columns or any row based on a condition

In [390]:
## drop a column salary

my_table.drop("salary", axis = 1)

        name       city        deptt
0      rohan      delhi      finance
1      mohan     mumbai    marketing
2      shyam      delhi  engineering
3  ghanshyam  hyderabad           HR
4      sohan     mumbai        admin

In [392]:
my_table.drop(2)  # dropping the index 2

        name       city  salary      deptt
0      rohan      delhi   10000    finance
1      mohan     mumbai   12000  marketing
3  ghanshyam  hyderabad    9000         HR
4      sohan     mumbai   18000      admin

In [397]:
my_table

        name       city  salary        deptt
0      rohan      delhi   10000      finance
1      mohan     mumbai   12000    marketing
2      shyam      delhi   15000  engineering
3  ghanshyam  hyderabad    9000           HR
4      sohan     mumbai   18000        admin

In [396]:
my_table.drop(my_table[my_table["city"] == "mumbai"].index)

        name       city  salary        deptt
0      rohan      delhi   10000      finance
2      shyam      delhi   15000  engineering
3  ghanshyam  hyderabad    9000           HR

In [402]:
## drop all the rows where the city is mumbai
except_mumbai =  my_table[~(my_table["city"] == "mumbai")]  # filter opposite of city == 'mumbai'

In [403]:
except_mumbai

        name       city  salary        deptt
0      rohan      delhi   10000      finance
2      shyam      delhi   15000  engineering
3  ghanshyam  hyderabad    9000           HR

In [404]:
my_table

        name       city  salary        deptt
0      rohan      delhi   10000      finance
1      mohan     mumbai   12000    marketing
2      shyam      delhi   15000  engineering
3  ghanshyam  hyderabad    9000           HR
4      sohan     mumbai   18000        admin

In [405]:
my_table[my_table["salary"] > 10000]

    name    city  salary        deptt
1  mohan  mumbai   12000    marketing
2  shyam   delhi   15000  engineering
4  sohan  mumbai   18000        admin

## Str methods in dataframe

In [407]:
# convert the names to title case

emp_table

        name       city  salary        deptt  salary_more_than_average
0      rohan      delhi   10000      finance                     False
1      mohan     mumbai   12000    marketing                      True
2      shyam      delhi   15000  engineering                      True
3  ghanshyam  hyderabad    9000           HR                     False
4      sohan     mumbai   18000        admin                      True
5     Mahesh    kolkata    4000           HR                     False
6     Ramesh    kolkata    8000  engineering                     False

In [413]:
emp_table["corrected_name"] =  emp_table["name"].str.title()
emp_table

,name,city,salary,deptt,salary_more_than_average,corrected_name
0,rohan,delhi,10000,finance,False,Rohan
1,mohan,mumbai,12000,marketing,True,Mohan
2,shyam,delhi,15000,engineering,True,Shyam
3,ghanshyam,hyderabad,9000,HR,False,Ghanshyam
4,sohan,mumbai,18000,admin,True,Sohan
5,Mahesh,kolkata,4000,HR,False,Mahesh
6,Ramesh,kolkata,8000,engineering,False,Ramesh

In [409]:
emp_table["name"].apply(lambda x: x.title())

0        Rohan
1        Mohan
2        Shyam
3    Ghanshyam
4        Sohan
5       Mahesh
6       Ramesh
Name: name, dtype: object

# pivot table

# crosstabs

In [414]:
emp_table

,name,city,salary,deptt,salary_more_than_average,corrected_name
0,rohan,delhi,10000,finance,False,Rohan
1,mohan,mumbai,12000,marketing,True,Mohan
2,shyam,delhi,15000,engineering,True,Shyam
3,ghanshyam,hyderabad,9000,HR,False,Ghanshyam
4,sohan,mumbai,18000,admin,True,Sohan
5,Mahesh,kolkata,4000,HR,False,Mahesh
6,Ramesh,kolkata,8000,engineering,False,Ramesh

In [416]:
pd.crosstab(emp_table["city"], emp_table["deptt"])

deptt      HR  admin  engineering  finance  marketing
city
delhi       0      0            1        1          0
hyderabad   1      0            0        0          0
kolkata     1      0            1        0          0
mumbai      0      1            0        0          1

In [417]:
pd.crosstab(emp_table["city"], emp_table["deptt"], values = emp_table["salary"], aggfunc="mean")

deptt          HR    admin  engineering  finance  marketing
city
delhi         NaN      NaN      15000.0  10000.0        NaN
hyderabad  9000.0      NaN          NaN      NaN        NaN
kolkata    4000.0      NaN       8000.0      NaN        NaN
mumbai        NaN  18000.0          NaN      NaN    12000.0

In [419]:
city_wise_salary_aggregate =  pd.crosstab(emp_table["city"],
            emp_table["deptt"], 
            values = emp_table["salary"], 
            aggfunc="mean").fillna(0)

city_wise_salary_aggregate

deptt          HR    admin  engineering  finance  marketing
city
delhi         0.0      0.0      15000.0  10000.0        0.0
hyderabad  9000.0      0.0          0.0      0.0        0.0
kolkata    4000.0      0.0       8000.0      0.0        0.0
mumbai        0.0  18000.0          0.0      0.0    12000.0

# groupby transform

# dealing with datetime objects

# practicing with str methods on dataframe